// Generated by scripts/generate-pwa-assets.mjs from packages/config/tailwind/tokens.css.
// Do not edit: change the tokens and run the script again.
export const PWA_COLORS = {
  theme: '#047857',
  background: '#f9fafb',
  mark: '#ffffff',
} as const;
